before_script:
- npm update -g npm
sudo: required
language: node_js
node_js:
- '0.12'
services: 
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: AwqMBbiQ7SnnH4VgIgb64jBRPHGGPBlWO3hS/a1Is6TAn5T5813zVgcLdSqSzfldU8SC5m6De1lvf2KCsrKSU4Uwwiorf/TvJzpqFfHbBrn+adERzlge/VXoBmuxjKBk3MufuqS+8KlGG+VaCJROEcaZQx4MKq+PNsa6qRmmBSHU6Kf2vt7YjGWAV5bfg7AbRYbNXiC9Xk78M9ANn0YuXYQ59pSNx6lml3rjOhA/YXPzP4cdBlwuN8BCje67G8SUr3GgcZXOMjZ+rCpzqWbWc2phcFRpPVXy4sk7LL2JCWhDbMlg+Rk+ILy4hYEEuynRTFHnbWjYwH94pUkGy05YtnOXFGMoJklMoQNSyZFBxhPn/f6L2mjTYdn6+tOEOH/M4Lf3w/TE287pg/WKpMKkxVY7m6NtQCmOxlfWp+KuOg1s9/MRgv5nAlh9hp8RBA5oJH9+z6YKNRBzEJDM3enAQDzup2N8WQxBljcu+hdwvXfRwl+Kwxf7pjm+zo12zgGDgCF1hQo1mq9Zr97HrRUSupZGhkkOVFwNNdhWY/0KzdcewtwpuDQdGBeS36wZkkvyXDWR0YWGxSSbu4i1TBBKHjgHsm7V8fSaejtTC68RZiGyifdLG6S4LSDaeCpPK3E3CdOAgqMGXp5wUbw9EzEgGJ3tRVPG7Xt0F24apBiCzUk=
